// src/api/catalog.ts
// ⚠️  이 파일은 scripts/generate-mcp-code.js로 자동 생성됩니다.
// ⚠️  직접 편집하지 마세요. 스펙 수정 후 generate-mcp-code.js를 다시 실행하세요.
// 생성일시: 2026-04-24T00:55:52.022Z
// 항목 수: 157개

export type FiscalCategory = "budget" | "settlement" | "execution" | "stats" | "project" | "levy";
export type FiscalSource = "openfiscal";

export interface CatalogEntry {
  readonly code: string;
  readonly name: string;
  readonly category: FiscalCategory;
  readonly source: FiscalSource;
  readonly description: string;
  readonly requiredParams: string[];
  readonly optionalParams: string[];
}

export const FISCAL_CATALOG: readonly CatalogEntry[] = [
  // ── 예산 ──────────────────────────────────────────────────────────
  {
    code: "ExpenditureBudgetInit5",
    name: "세부사업 예산편성현황(총액)",
    category: "budget",
    source: "openfiscal",
    description: "세출이란 국가 또는 지방자치단체가 한 회계년도 동안에 모든 수요",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)", "SACTV_NM(세부사업명)", "BZ_CLS_NM(사업분류명)"],
  },
  {
    code: "ExpenditureBudgetInit6",
    name: "세목 예산편성현황(총액)",
    category: "budget",
    source: "openfiscal",
    description: "세출이란 국가 또는 지방자치단체가 한 회계년도 동안에 모든 수요",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)", "SACTV_NM(세부사업명)", "CITM_NM(지출목명)", "EITM_NM(지출세목명)", "BZ_CLS_NM(사업분류명)"],
  },
  {
    code: "TotalExpenditure5",
    name: "세부사업 예산편성현황(총지출)",
    category: "budget",
    source: "openfiscal",
    description: "단년도, 세출/지출 예산편성 현황을 총지출 기준, 세출순계 기준",
    requiredParams: ["FSCL_YY(회계연도)", "BDG_FND_DIV_CD(전체예산기금구분코드(0:전체, 1:예산, 5:기금))", "ANEXP_INQ_STND_CD(세출조회기준코드(1:총지출, 2:세출순계))"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)", "SACTV_NM(세부사업명)", "BZ_CLS_NM(사업분류명)"],
  },
  {
    code: "TotalExpenditure6",
    name: "세목 예산편성현황(총지출)",
    category: "budget",
    source: "openfiscal",
    description: "단년도, 세출/지출 예산편성 현황을 총지출 기준, 세출순계 기준",
    requiredParams: ["FSCL_YY(회계연도)", "BDG_FND_DIV_CD(전체예산기금구분코드(0:전체, 1:예산, 5:기금))", "ANEXP_INQ_STND_CD(세출조회기준코드(1:총지출, 2:세출순계))"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)", "SACTV_NM(세부사업명)", "CITM_NM(지출목명)", "EITM_NM(지출세목명)", "BZ_CLS_NM(사업분류명)"],
  },
  {
    code: "ForeignExpenditureBudgget5",
    name: "세부사업 예산편성현황(외화)",
    category: "budget",
    source: "openfiscal",
    description: "세출이란 국가 또는 지방자치단체가 한 회계년도 동안에 모든 수요",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)", "SACTV_NM(세부사업명)", "BZ_CLS_NM(사업분류명)"],
  },
  {
    code: "ForeignExpenditureBudgget6",
    name: "세목 예산편성현황(외화)",
    category: "budget",
    source: "openfiscal",
    description: "세출이란 국가 또는 지방자치단체가 한 회계년도 동안에 모든 수요",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)", "SACTV_NM(세부사업명)", "CITM_NM(지출목명)", "EITM_NM(지출세목명)", "BZ_CLS_NM(사업분류명)"],
  },
  {
    code: "ExpenditureBudgetAdd7",
    name: "세출 세부사업 예산편성현황(추경포함)",
    category: "budget",
    source: "openfiscal",
    description: "- 예산은 추경이 반영된 자료입니다. - 추가경정예산은 예산이",
    requiredParams: ["FSCL_YY(회계연도)", "SBUDG_DGR(추경차수)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)", "SACTV_NM(세부사업명)", "BZ_CLS_NM(사업분류명)"],
  },
  {
    code: "ExpenditureBudgetAdd8",
    name: "세출 세목 예산편성현황(추경포함)",
    category: "budget",
    source: "openfiscal",
    description: "- 예산은 추경이 반영된 자료입니다. - 추가경정예산은 예산이",
    requiredParams: ["FSCL_YY(회계연도)", "SBUDG_DGR(추경차수)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)", "SACTV_NM(세부사업명)", "CITM_NM(지출목명)", "EITM_NM(지출세목명)", "BZ_CLS_NM(사업분류명)"],
  },
  {
    code: "BudgetRevenuesInit2",
    name: "예산편성현황(총액)",
    category: "budget",
    source: "openfiscal",
    description: "세입은 국가 또는 지방자치단체의 1회계 연도에 있어서의 국가 또",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "IKWAN_NM(수입관명)", "IHANG_NM(수입항명)", "IMOK_NM(수입목명)"],
  },
  {
    code: "TotalRevenue2",
    name: "예산편성현황(총수입)",
    category: "budget",
    source: "openfiscal",
    description: "단년도, 세입/수입 예산편성 현황을 총수입 기준, 세입순계 기준",
    requiredParams: ["FSCL_YY(회계연도)", "REVN_INQ_STND_CD(예산편성집계구분코드)", "BDG_FND_DIV_CD(전체예산기금구분코드)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "IKWAN_NM(수입관명)", "IHANG_NM(수입항명)", "IMOK_NM(수입목명)"],
  },
  {
    code: "ForeignRevenueIncomeBudget2",
    name: "예산편성현황(외화)",
    category: "budget",
    source: "openfiscal",
    description: "세입은 국가 또는 지방자치단체의 1회계 연도에 있어서의 국가 또",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "IKWAN_NM(수입관명)", "IHANG_NM(수입항명)", "IMOK_NM(수입목명)"],
  },
  {
    code: "BudgetRevenuesAdd3",
    name: "세입 예산편성현황(추경포함)",
    category: "budget",
    source: "openfiscal",
    description: "- 예산은 추경이 반영된 자료입니다. - 추가경정예산은 예산이",
    requiredParams: ["FSCL_YY(회계연도)", "SBUDG_DGR(추경차수)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "IKWAN_NM(수입관명)", "IHANG_NM(수입항명)", "IMOK_NM(수입목명)"],
  },
  {
    code: "RevenuesSettled",
    name: "세입/수입 결산 현황",
    category: "budget",
    source: "openfiscal",
    description: "정부의 세입/수입에 관한 결산정보입니다.",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)", "ACCT_NM(계정명)", "FSCL_NM(회계명)"],
  },
  {
    code: "ExpendituresSettlement",
    name: "세출/지출 결산 현황",
    category: "budget",
    source: "openfiscal",
    description: "정부의 세출/지출에 관한 결산정보입니다.",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)"],
  },
  {
    code: "ClosingFundRevenuesExpenses",
    name: "기금별 수입/지출 결산 현황",
    category: "budget",
    source: "openfiscal",
    description: "기금의 수입/지출에 관한 결산보고서 입니다.",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["FSCL_NM(회계명)"],
  },
  {
    code: "AnnualSurplusBudget",
    name: "세계잉여금",
    category: "budget",
    source: "openfiscal",
    description: "총세입에서 총세출을 차감한 것을 결산상 잉여금이라 하고, 결산상",
    requiredParams: [],
    optionalParams: ["OJ_YY(기준년도)"],
  },
  {
    code: "BudgetBalance",
    name: "재정수지",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: [],
    optionalParams: ["OJ_YY(기준년도)"],
  },
  {
    code: "TotalExpenditure",
    name: "(OPEN API) 세출/지출 예산편성현황(총지출)",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)", "ANEXP_INQ_STND_CD(조회기준)", "BDG_FND_DIV_CD(예산기금구분)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부분명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)"],
  },
  {
    code: "TotalExpenditure1",
    name: "(OPEN API) 세출/지출 세부사업 예산편성현황(총지출)",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)", "SACTV_NM(세부사업명)", "ANEXP_INQ_STND_CD(조회기준)", "BDG_FND_DIV_CD(예산기금구분)"],
  },
  {
    code: "TotalExpenditure2",
    name: "(OPEN API) 세출/지출 세목 예산편성현황(총지출)",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)", "SACTV_NM(세부사업명)", "CITM_NM(목명)", "EITM_NM(세목명)", "ANEXP_INQ_STND_CD(조회기준)", "BDG_FND_DIV_CD(예산기금구분)"],
  },
  {
    code: "ForeignExpenditureBudgget",
    name: "(OPEN API) 세출/지출 예산편성현황(외화)",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)"],
  },
  {
    code: "ExpenditureBudgetInit1",
    name: "(OPEN API) 세출/지출 세부사업 예산편성현황(총액)",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계년도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)", "SACTV_NM(세부사업명)"],
  },
  {
    code: "ForeignExpenditureBudgget1",
    name: "(OPEN API) 세출/지출 세부사업 예산편성현황(외화)",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계년도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)", "SACTV_NM(세부사업명)"],
  },
  {
    code: "ExpenditureBudgetInit2",
    name: "(OPEN API) 세출/지출 세목 예산편성현황(총액)",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계년도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)", "SACTV_NM(세부사업명)", "CITM_NM(목명)", "EITM_NM(세목명)"],
  },
  {
    code: "ForeignExpenditureBudgget2",
    name: "(OPEN API) 세출/지출 세목 예산편성현황(외화)",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계년도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)", "SACTV_NM(세부사업명)", "CITM_NM(목명)", "EITM_NM(세목명)"],
  },
  {
    code: "ExpenditureBudgetAdd5",
    name: "(OPEN API) 세출 세부사업 예산편성현황(추경포함)",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["SBUDG_DGR(추경횟수)", "OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)", "SACTV_NM(세부사업명)", "BZ_CLS_NM(경비구분)"],
  },
  {
    code: "ExpenditureBudgetInit",
    name: "(OPEN API) 세출/지출 예산편성현황(총액)",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)"],
  },
  {
    code: "ExpenditureBudgetAdd",
    name: "(OPEN API) 세출 예산편성현황(추경포함)",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)"],
  },
  {
    code: "ExpenditureBudgetInit3",
    name: "(OPEN API) 세출/지출 세부사업 예산편성현황(총액)",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계년도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)", "SACTV_NM(세부사업명)", "BZ_CLS_NM(경비구분)"],
  },
  {
    code: "ExpenditureBudgetInit4",
    name: "(OPEN API) 세출/지출 세목 예산편성현황(총액)",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계년도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)", "SACTV_NM(세부사업명)", "CITM_NM(목명)", "EITM_NM(세목명)", "BZ_CLS_NM(경비구분)"],
  },
  {
    code: "ForeignExpenditureBudgget3",
    name: "(OPEN API) 세출/지출 세부사업 예산편성현황(외화)",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계년도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)", "SACTV_NM(세부사업명)", "BZ_CLS_NM(경비구분)"],
  },
  {
    code: "ExpenditureBudgetAdd4",
    name: "(OPEN API) 세출 세목 예산편성현황(추경포함)",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계년도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)", "SACTV_NM(세부사업명)", "CITM_NM(목명)", "EITM_NM(세목명)", "BZ_CLS_NM(경비구분)"],
  },
  {
    code: "ExpenditureBudgetAdd6",
    name: "(OPEN API) 세출 세목 예산편성현황(추경포함)",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계년도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)", "SACTV_NM(세부사업명)", "CITM_NM(목명)", "EITM_NM(세목명)", "BZ_CLS_NM(경비구분)", "SBUDG_DGR(추경횟수)"],
  },
  {
    code: "ForeignExpenditureBudgget4",
    name: "(OPEN API) 세출/지출 세목 예산편성현황(외화)",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계년도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)", "SACTV_NM(세부사업명)", "CITM_NM(목명)", "EITM_NM(세목명)", "BZ_CLS_NM(경비구분)"],
  },
  {
    code: "GEAportal",
    name: "(OPEN API) 세부사업 예산편성현황(추경포함-범정부EA포털 제공용)",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_CD(소관)", "FSCL_CD(회계)", "ACCT_CD(계정)", "FLD_CD(분야)", "SECT_CD(부문)", "PGM_CD(프로그램)", "ACTV_CD(단위사업)", "SACTV_CD(세부사업)", "BZ_CLS_CD(경비)", "SBUDG_DGR(추경차수)"],
  },
  {
    code: "TotalRevenue",
    name: "(OPEN API) 세입/수입 예산편성현황(총수입)",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)", "REVN_INQ_STND_CD(조회기준)", "BDG_FND_DIV_CD(예산기금구분)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "IKWAN_NM(수입관명)", "IHANG_NM(수입항명)", "IMOK_NM(수입목명)"],
  },
  {
    code: "ForeignRevenueIncomeBudget",
    name: "(OPEN API) 세입/수입 예산편성현황(외화)",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "IKWAN_NM(수입관명)", "IHANG_NM(수입항명)", "IMOK_NM(수입목명)"],
  },
  {
    code: "BudgetRevenuesInit",
    name: "(OPEN API) 세입/수입 예산편성현황(총액)",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "IKWAN_NM(수입관명)", "IHANG_NM(수입항명)", "IMOK_NM(수입목명)"],
  },
  {
    code: "BudgetRevenuesAdd2",
    name: "(OPEN API) 세입 예산편성현황(추경포함)",
    category: "budget",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "IKWAN_NM(수입관명)", "IHANG_NM(수입항명)", "IMOK_NM(수입목명)", "SBUDG_DGR(추경횟수)"],
  },
  // ── 결산·재무제표 ─────────────────────────────────────────────────────
  {
    code: "OPFI140",
    name: "연도별총세입·총세출예산및결산",
    category: "settlement",
    source: "openfiscal",
    description: "연도별 세계잉여금을 회계구분별 현황 정보입니다.",
    requiredParams: [],
    optionalParams: ["ACNT_YR(회계연도)"],
  },
  {
    code: "DepartRevenExpenSettle",
    name: "소관별 세입/세출 결산 현황",
    category: "settlement",
    source: "openfiscal",
    description: "국가통합 중앙관서별 세입세출결산 총괄보고서 정보입니다. (200",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)"],
  },
  {
    code: "FiacalRevenExpenSettle",
    name: "회계별 세입/세출 결산 현황",
    category: "settlement",
    source: "openfiscal",
    description: "중앙정부 회계별 세입세출결산 총괄보고서 정보입니다. (2007회",
    requiredParams: ["FSCL_YY(회계년도)"],
    optionalParams: ["GBN_NM(회계구분명)", "FSCL_NM(회계명)"],
  },
  {
    code: "FiscalRevenSettle",
    name: "회계별 세입 결산 현황",
    category: "settlement",
    source: "openfiscal",
    description: "국가통합 회계별 세입결산보고서 정보입니다. (2007회계년도부터",
    requiredParams: ["FSCL_YY(회계년도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)"],
  },
  {
    code: "FiscalExpenSettle",
    name: "회계별 세출 결산 현황",
    category: "settlement",
    source: "openfiscal",
    description: "국가통합 회계별 세출결산보고서 정보입니다. (2007회계년도부터",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)"],
  },
  {
    code: "VW_FOAC007",
    name: "재정상태표",
    category: "settlement",
    source: "openfiscal",
    description: "국가통합 재무제표 중 재정상태표 정보입니다. (2011회계년도부",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: [],
  },
  {
    code: "VW_FOAC008",
    name: "재정운영표",
    category: "settlement",
    source: "openfiscal",
    description: "국가통합 재무제표 중 재정운영표 정보입니다. (2011회계년도부",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: [],
  },
  {
    code: "VW_FOAC004",
    name: "소관별 재정상태표",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: [],
    optionalParams: ["OFFC_NM(소관명)"],
  },
  {
    code: "VW_FOAC005",
    name: "소관별 재정운영표",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)"],
  },
  {
    code: "VW_FOAC006",
    name: "소관별 순자산변동표",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)"],
  },
  {
    code: "VW_FOAC001",
    name: "회계·기금별 재정상태표",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["FSCL2_NM(회계명)"],
  },
  {
    code: "VW_FOAC002",
    name: "회계·기금별 재정운영표",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["FSCL2_NM(회계명)"],
  },
  {
    code: "VW_FOAC003",
    name: "회계·기금별 순자산변동표",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["FSCL2_NM(회계명)"],
  },
  {
    code: "VW_FOAC034",
    name: "성질별재정운영표",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: [],
  },
  {
    code: "VW_FOAC035",
    name: "현금흐름표",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: [],
  },
  {
    code: "VW_FOAC026",
    name: "소관별 재정상태표(확장)",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)"],
  },
  {
    code: "VW_FOAC027",
    name: "소관별 재정운영표(확장)",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)"],
  },
  {
    code: "VW_FOAC028",
    name: "소관별 순자산변동표(확장)",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)"],
  },
  {
    code: "VW_FOAC029",
    name: "소관별 성질별재정운영표",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)"],
  },
  {
    code: "VW_FOAC030",
    name: "소관별 현금흐름표",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)"],
  },
  {
    code: "VW_FOAC021",
    name: "회계·기금별 재정상태표(확장)",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["FSCL2_NM(회계명)"],
  },
  {
    code: "VW_FOAC022",
    name: "회계·기금별 재정운영표(확장)",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["FSCL2_NM(회계명)"],
  },
  {
    code: "VW_FOAC023",
    name: "회계·기금별 순자산변동표(확장)",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["FSCL2_NM(회계명)"],
  },
  {
    code: "VW_FOAC024",
    name: "회계·기금별 성질별재정운영표",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["FSCL2_NM(회계명)"],
  },
  {
    code: "VW_FOAC025",
    name: "회계·기금별 현금흐름표",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["FSCL2_NM(회계명)"],
  },
  {
    code: "OPFI205",
    name: "통합재정수지(86GFS결산)",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI206",
    name: "수입의경제적분류(86GFS결산)",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI207",
    name: "지출및순융자의경제적분류(86GFS결산)",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI208",
    name: "지출및순융자의기능적분류(86GFS결산)",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI209",
    name: "순융자(86GFS결산)",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI210",
    name: "보전재원(86GFS결산)",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI211",
    name: "내부거래(86GFS결산)",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI217",
    name: "재정상태표(01GFS)",
    category: "settlement",
    source: "openfiscal",
    description: "",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  // ── 집행 ──────────────────────────────────────────────────────────
  {
    code: "OPFI113",
    name: "총지출기준집행추이",
    category: "execution",
    source: "openfiscal",
    description: "정부의 총지출 기준의 집행액 현황 정보입니다.",
    requiredParams: [],
    optionalParams: ["ACNT_YR(회계연도)"],
  },
  {
    code: "OPFI114",
    name: "회계·기금별집행추이",
    category: "execution",
    source: "openfiscal",
    description: "정부가 총지출 기준의 집행액을 회계기금별로 분류한 현황 정보입니",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI115",
    name: "회계·기금별이월추이",
    category: "execution",
    source: "openfiscal",
    description: "정부의 총지출 기준 회계기금별 이월액 현황 정보입니다.",
    requiredParams: [],
    optionalParams: ["ACNT_YR(회계연도)"],
  },
  {
    code: "OPFI116",
    name: "회계·기금별불용추이",
    category: "execution",
    source: "openfiscal",
    description: "정부의 총지출 기준 회계기금별 불용액 현황 정보입니다.",
    requiredParams: [],
    optionalParams: ["ACNT_YR(회계연도)"],
  },
  {
    code: "OPFI118",
    name: "분야별이월추이",
    category: "execution",
    source: "openfiscal",
    description: "정부가 차년도로 이월한 예산을 분야별로 분류한 현황 정보입니다.",
    requiredParams: [],
    optionalParams: ["ACNT_YR(회계연도)"],
  },
  {
    code: "OPFI119",
    name: "분야별불용추이",
    category: "execution",
    source: "openfiscal",
    description: "정부가 차년도로 불용한 예산을 분야별로 분류한 현황 정보입니다.",
    requiredParams: [],
    optionalParams: ["ACNT_YR(회계연도)"],
  },
  {
    code: "OPFI117",
    name: "분야별집행추이",
    category: "execution",
    source: "openfiscal",
    description: "정부가 총지출 기준의 집행액을 분야별로 분류한 현황 정보입니다.",
    requiredParams: [],
    optionalParams: ["ACNT_YR(회계연도)"],
  },
  {
    code: "OPFI120",
    name: "성질별집행추이",
    category: "execution",
    source: "openfiscal",
    description: "정부의 총지출 기준 지출성질목별 집행액 현황 정보입니다.",
    requiredParams: [],
    optionalParams: ["ACNT_YR(회계연도)"],
  },
  {
    code: "OPFI121",
    name: "이월의성질별추이",
    category: "execution",
    source: "openfiscal",
    description: "정부가 차년도로 이월한 예산을 지출성질목별로 분류한 현황 정보입",
    requiredParams: [],
    optionalParams: ["ACNT_YR(회계연도)"],
  },
  {
    code: "OPFI122",
    name: "불용성질별추이",
    category: "execution",
    source: "openfiscal",
    description: "정부의 총지출 기준 지출성질목별 불용액 현황 정보입니다.",
    requiredParams: [],
    optionalParams: ["ACNT_YR(회계연도)"],
  },
  {
    code: "VWFORM",
    name: "월별 수입징수상황",
    category: "execution",
    source: "openfiscal",
    description: "월별 세입 예산/기금 운용 집행실적 공개(수입목별)",
    requiredParams: [],
    optionalParams: ["FSCL_YY(회계연도)", "EXE_M(회계월)", "OFFC_CD(소관코드       소관코드 검색)", "FSCL_CD(회계코드       회계코드 검색)"],
  },
  {
    code: "VWFORM2",
    name: "월별 수입운용상황",
    category: "execution",
    source: "openfiscal",
    description: "월별 세입 예산/기금 운용 집행실적 공개(수입항별)",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["EXE_M(회계월)", "OFFC_CD(소관코드       소관코드 검색)", "FSCL_CD(회계코드       회계코드 검색)"],
  },
  {
    code: "VWFORD",
    name: "일별 수입운용상황",
    category: "execution",
    source: "openfiscal",
    description: "일별 세입 예산/기금 운용 집행실적 공개(수입항별)",
    requiredParams: ["OFFC_CD(소관코드       소관코드 검색)"],
    optionalParams: ["FSCL_YY(회계연도)", "FSCL_CD(회계코드       회계코드 검색)", "ACCT_CD(계정코드)"],
  },
  {
    code: "VWFOEM",
    name: "월별 지출집행상황",
    category: "execution",
    source: "openfiscal",
    description: "월별 지출 예산/기금 운용 집행실적 공개(단위사업별)",
    requiredParams: ["OFFC_CD(소관코드       소관코드 검색)"],
    optionalParams: ["FSCL_YY(회계연도)", "EXE_M(집행월)", "FSCL_CD(회계코드       회계코드 검색)"],
  },
  {
    code: "VWFOEM2",
    name: "월별 지출운용상황",
    category: "execution",
    source: "openfiscal",
    description: "월별 세출 예산/기금 운용 집행실적 공개(세부사업별)",
    requiredParams: ["FSCL_YY(회계연도)", "EXE_M(집행연월)", "OFFC_CD(소관코드       소관코드 검색)"],
    optionalParams: ["FSCL_CD(회계코드       회계코드 검색)"],
  },
  {
    code: "VWFOED",
    name: "일별 지출운용상황",
    category: "execution",
    source: "openfiscal",
    description: "일별 세출 예산/기금 운용 집행실적 공개(세부사업별)",
    requiredParams: ["FSCL_YY(회계연도)", "EXE_M(집행연월)"],
    optionalParams: ["EXE_DATE(집행일자)", "OFFC_CD(소관코드       소관코드 검색)", "FSCL_CD(회계코드       회계코드 검색)"],
  },
  {
    code: "VW_FOBM303",
    name: "공공기관별 주요관리대상사업 집행실적",
    category: "execution",
    source: "openfiscal",
    description: "월간재정동향_공공기관 집행실적에 관한 정보이며 21회계년도까지의",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["ACTV_NM(단위사업명)", "OG_NM(공공기관명)"],
  },
  // ── 총사업비 ────────────────────────────────────────────────────────
  {
    code: "TotalProjectCost",
    name: "총사업비현황",
    category: "project",
    source: "openfiscal",
    description: "총사업비관리제도란 국가의 예산 또는 기금으로 시행하는 대규모 재",
    requiredParams: ["FSCL_YY(회계년도)"],
    optionalParams: ["TBCOST_NM(총사업비명)", "TBCOST_BZ_TY_NM(사업유형)", "OFFC_NM(소관명)"],
  },
  // ── 부담금 ─────────────────────────────────────────────────────────
  {
    code: "LevyingAmount",
    name: "부담금운용현황",
    category: "levy",
    source: "openfiscal",
    description: "○ 부담금은 \"특정 공익사업과 관련하여 법률이 정하는 바에 따라",
    requiredParams: [],
    optionalParams: ["OJ_YY(대상연도)"],
  },
  // ── 재정통계 ────────────────────────────────────────────────────────
  {
    code: "OPFI156",
    name: "재정수입구조(본예산총수입기준)",
    category: "stats",
    source: "openfiscal",
    description: "본예산의 총수입 기준의 회계별, 세목별 수입구조 현황 정보입니다",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI157",
    name: "국세수입추이",
    category: "stats",
    source: "openfiscal",
    description: "국세는 내국세(소득세, 법인세, 부가가치세 등 8개)와 관세,",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI141",
    name: "조세부담률및국민부담률추이",
    category: "stats",
    source: "openfiscal",
    description: "국민 부담 현황 정보입니다.",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI158",
    name: "일반·특별회계세외수입추이",
    category: "stats",
    source: "openfiscal",
    description: "정부 세외수입 중 회계별 세외수입금 현황 정보입니다.",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI159",
    name: "기금수입추이",
    category: "stats",
    source: "openfiscal",
    description: "정부 세외수입 중 수입관명에 따른 세외수입금 현황 정보입니다.",
    requiredParams: [],
    optionalParams: ["ACNT_YR(회계연도)"],
  },
  {
    code: "OPFI171",
    name: "재정지출추이(본예산총지출기준)",
    category: "stats",
    source: "openfiscal",
    description: "정부의 본예산 기준 일반회계, 특별회계, 기금별 총지출 규모 현",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI160",
    name: "재정지출추이(총계기준)",
    category: "stats",
    source: "openfiscal",
    description: "정부의 총계 기준 일반회계, 특별회계, 기금별 순지출 규모 현황",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI161",
    name: "특별회계별재정지출추이(총지출기준)",
    category: "stats",
    source: "openfiscal",
    description: "특정한 목적을 위해 운영되는 특별회계의 회계별 총지출 규모 현황",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI162",
    name: "기금성격별운용규모(총지출기준)",
    category: "stats",
    source: "openfiscal",
    description: "기금운용 성격별(사업성기금, 사회보험성기금, 계정성기금) 총지출",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI163",
    name: "사업성기금운용규모(총지출기준)",
    category: "stats",
    source: "openfiscal",
    description: "사업성 기금의 회계별(주택도시기금, 국민체육진흥기금 등) 총지출",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI164",
    name: "기금운용구분별운용규모(총지출기준)",
    category: "stats",
    source: "openfiscal",
    description: "기금운용 구분별(사업비, 기금운영비, 차입금이자상환) 총지출 규",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI165",
    name: "16대분야별재원배분(총지출기준)",
    category: "stats",
    source: "openfiscal",
    description: "16대 분야별 총지출기준의 재원배분 현황 정보입니다.",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI166",
    name: "중앙관서별총지출추이",
    category: "stats",
    source: "openfiscal",
    description: "정부 중앙관서별 총지출 현황 정보입니다.",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI123",
    name: "성질별지출추이",
    category: "stats",
    source: "openfiscal",
    description: "정부의 재정지출을 목별 현황 정보입니다.",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI124",
    name: "인건비편성사업지출추이",
    category: "stats",
    source: "openfiscal",
    description: "정부 예산 편성 및 집행시 인건비 항목에 할당된 사업 예산의 회",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI125",
    name: "기본경비추이",
    category: "stats",
    source: "openfiscal",
    description: "정부 운영에 필수적인 기본경비(인건비, 물건비, 자산취득 등)",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI126",
    name: "본예산기준인건비,경비,사업비추이",
    category: "stats",
    source: "openfiscal",
    description: "본예산 기준의 인건비·기본경비·주요사업비 세출예산금액 현황 정보",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI127",
    name: "자본지출현황",
    category: "stats",
    source: "openfiscal",
    description: "정부의 지출성질목별 지출액 현황 정보입니다.",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI128",
    name: "분야별출자금추이",
    category: "stats",
    source: "openfiscal",
    description: "정부의 분야별 출자금 현황 정보입니다.",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI129",
    name: "분야별융자지출추이",
    category: "stats",
    source: "openfiscal",
    description: "정부의 분야별 융자지출액 현황 정보입니다.",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI130",
    name: "분야별이차보전지출추이",
    category: "stats",
    source: "openfiscal",
    description: "정부가 정부의 직접 자금지원 금리와 금융 기관 대출에서의 금리차",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI131",
    name: "국고보조사업지출추이",
    category: "stats",
    source: "openfiscal",
    description: "국고보조사업의 지출세목별(민간경상보조, 민간자본보조, 자치단체경",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI132",
    name: "분야별국고보조사업지출추이",
    category: "stats",
    source: "openfiscal",
    description: "분아별(일반행정, 교육, 사회복지 등) 국고보조사업 지출 규모",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI133",
    name: "출연금지출추이",
    category: "stats",
    source: "openfiscal",
    description: "정부가 법령이나 조례에 근거하여 공공 목적을 위해 민간 또는 공",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI134",
    name: "분야별출연금지출추이",
    category: "stats",
    source: "openfiscal",
    description: "분아별(일반행정, 교육, 사회복지 등) 출연금 지출 규모 현황",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI150",
    name: "작성기준별주요재정통계(중앙정부기준)",
    category: "stats",
    source: "openfiscal",
    description: "재정수지의 작성 기준별 현황 정보입니다.",
    requiredParams: [],
    optionalParams: ["ACNT_YR(회계연도)"],
  },
  {
    code: "OPFI152",
    name: "성질별국가채무추이",
    category: "stats",
    source: "openfiscal",
    description: "국가채무(D1) 정보로 적자성채무, 금융성채무 정보 입니다.",
    requiredParams: [],
    optionalParams: ["ACNT_YR(회계연도)"],
  },
  {
    code: "OPFI168",
    name: "연도별지방교부세추이",
    category: "stats",
    source: "openfiscal",
    description: "중앙정부가 국가재정 균형을 위해 지방자치단체에 교부한 재원에 대",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI170",
    name: "연도별교육재정교부금추이",
    category: "stats",
    source: "openfiscal",
    description: "중앙정부가 지방교육재정교부금법에 따라 교육기관 및 교육행정기관에",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI167",
    name: "자치단체국고보조사업추이",
    category: "stats",
    source: "openfiscal",
    description: "지방자치단체가 수행하는 국고보조사업의 일반회계 및 특별회계 지원",
    requiredParams: [],
    optionalParams: ["ACNT_YR(회계연도)"],
  },
  {
    code: "OPFI172",
    name: "분야별 프로그램 예산",
    category: "stats",
    source: "openfiscal",
    description: "국가의 세출 예산을 16대 분야별 예산규모, 사업 건수 현황 정",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "GovOrdBz1",
    name: "정부구매예산",
    category: "stats",
    source: "openfiscal",
    description: "정부 발주사업 정보(예산)를 제공합니다. - 해당 금액은 성질별",
    requiredParams: ["FSCL_YY(회계년도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)", "FLD_NM(분야명)", "SECT_NM(부문명)", "PGM_NM(프로그램명)", "ACTV_NM(단위사업명)", "SACTV_NM(세부사업명)", "EITM_NM(비용성격)"],
  },
  {
    code: "National1",
    name: "국유재산 증감 및 현재액 총괄",
    category: "stats",
    source: "openfiscal",
    description: "본 통계는 결산 자료로, 매년 6월 초 전년 결산 정보가 공개됩",
    requiredParams: [],
    optionalParams: ["FSCL_YY(마감연도)"],
  },
  {
    code: "NationalProperty",
    name: "국유재산현황",
    category: "stats",
    source: "openfiscal",
    description: "<국유재산 정의> 넓은 의미의 국가가 소유하는 일체",
    requiredParams: [],
    optionalParams: ["OJ_YY(기준년도)"],
  },
  {
    code: "StateOwnedLands",
    name: "국유지현황",
    category: "stats",
    source: "openfiscal",
    description: "[국유지 정의] 국가가 소유하고 있는 토지를 말한다. 토지등기",
    requiredParams: [],
    optionalParams: ["OJ_YY(기준년도)"],
  },
  {
    code: "ConsignInvestPoolSizeQuarter",
    name: "연기금투자풀 수탁규모(분기별)",
    category: "stats",
    source: "openfiscal",
    description: "[연기금 투자풀 정의] 부족한 개별 연기금의 자산운용 전문성",
    requiredParams: [],
    optionalParams: ["OJ_YY(대상연도)"],
  },
  {
    code: "ConsignInvestPoolPeriodQuarter",
    name: "연기금투자풀 기간수익률(분기별)",
    category: "stats",
    source: "openfiscal",
    description: "[연기금 투자풀 정의] 부족한 개별 연기금의 자산운용 전문성",
    requiredParams: [],
    optionalParams: ["OJ_YY(대상년도)"],
  },
  {
    code: "ConsignInvestPoolSize",
    name: "연기금투자풀 수탁규모",
    category: "stats",
    source: "openfiscal",
    description: "[연기금 투자풀 정의] 부족한 개별 연기금의 자산운용 전문성",
    requiredParams: [],
    optionalParams: ["OJ_YY(기준년도)"],
  },
  {
    code: "ConsignInvestPoolPeriod",
    name: "연기금투자풀 기간수익률",
    category: "stats",
    source: "openfiscal",
    description: "[연기금 투자풀 정의] 부족한 개별 연기금의 자산운용 전문성",
    requiredParams: [],
    optionalParams: ["OJ_YY(기준년도)"],
  },
  {
    code: "FinanSecuriIssuanAndRedemp",
    name: "재정증권 발행 및 상환내역",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: ["FSCL_YY(회계연도)"],
    optionalParams: ["OFFC_NM(소관명)", "FSCL_NM(회계명)"],
  },
  {
    code: "ReceivedGovernment",
    name: "국가채권현황",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: [],
    optionalParams: ["OJ_YY(기준년도)"],
  },
  {
    code: "NRAccountingFund",
    name: "회계·기금별 국가채권 현황",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: [],
    optionalParams: ["OJ_YY(기준년도)"],
  },
  {
    code: "VW_FOCT002",
    name: "채권현재액명세서",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: [],
    optionalParams: ["FSCL_YY(회계연도)", "OFFC_NM(소관명)", "FSCL_NM(회계명)", "ACCT_NM(계정명)"],
  },
  {
    code: "GovernmentInvestment",
    name: "정부출자현황",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: [],
    optionalParams: ["OJ_YY(대상연도)", "OJ_M(대상월)", "INST_DIV_NM(기관구분)", "CGP_MAO_NM(주무부처)", "INST_NM(기관명)"],
  },
  {
    code: "GovernmentDividend",
    name: "정부출자기관 정부배당 현황",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: [],
    optionalParams: ["TRGT_YR(기준년도)", "IV_INST_NM(기관명)"],
  },
  {
    code: "GovernmentDebtYear",
    name: "국가채무(D1)",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: [],
    optionalParams: ["OJ_YY(기준년도)"],
  },
  {
    code: "OPFI197",
    name: "일반정부 부채(D2)",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: ["TRGT_YR(기준연도)"],
    optionalParams: [],
  },
  {
    code: "PublicDebtAndNationalDebt",
    name: "공공부문 부채(D3)",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: [],
    optionalParams: ["OJ_YY(기준년도)"],
  },
  {
    code: "SuretyLiabilityYear",
    name: "보증채무 현황",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: [],
    optionalParams: ["OJ_YY(기준년도)"],
  },
  {
    code: "TotalIncome",
    name: "총수입",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: [],
    optionalParams: ["OJ_YY(기준년도)"],
  },
  {
    code: "IncomeTax",
    name: "국세수입",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: [],
    optionalParams: ["OJ_YY(대상연도)", "OJ_M(대상월)"],
  },
  {
    code: "NontaxIncome",
    name: "세외수입",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: [],
    optionalParams: ["OJ_YY(대상연도)", "OJ_M(대상월)"],
  },
  {
    code: "FundIncome",
    name: "기금수입",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: [],
    optionalParams: ["OJ_YY(대상연도)", "OJ_M(대상월)"],
  },
  {
    code: "GrossExpend",
    name: "총지출",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: [],
    optionalParams: ["OJ_YY(기준년도)"],
  },
  {
    code: "GovernmentDebtMonth",
    name: "월별 국가채무(중앙정부)",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: [],
    optionalParams: ["OJ_YY(기준년도)", "OJ_M(기준월)"],
  },
  {
    code: "SuretyLiabilityMonth",
    name: "월별 보증채무 현황",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: [],
    optionalParams: ["OJ_YY(기준년도)", "OJ_M(기준월)"],
  },
  {
    code: "OPFI212",
    name: "정부운영표(01GFS)",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI213",
    name: "수익명세(01GFS)",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI214",
    name: "비용명세(01GFS)",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI215",
    name: "거래명세(01GFS)",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFI216",
    name: "거래외명세(01GFS)",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFB130",
    name: "중기 재정수입 전망",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFB133",
    name: "조세부담률 및 국민부담률",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: [],
    optionalParams: ["ACNT_YR(회계연도)"],
  },
  {
    code: "OPFB141",
    name: "중기 재정수지 전망",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFB140",
    name: "중기 재정지출 계획",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: ["ACNT_YR(회계연도)"],
    optionalParams: [],
  },
  {
    code: "OPFB129",
    name: "분야별 재원배분 계획",
    category: "stats",
    source: "openfiscal",
    description: "",
    requiredParams: [],
    optionalParams: ["ACNT_YR(회계연도)"],
  },
];

export function searchCatalog(opts: {
  keyword?: string;
  category?: FiscalCategory;
  source?: FiscalSource;
}): readonly CatalogEntry[] {
  return FISCAL_CATALOG.filter((entry) => {
    if (opts.category && entry.category !== opts.category) return false;
    if (opts.source && entry.source !== opts.source) return false;
    if (opts.keyword) {
      const lower = opts.keyword.toLowerCase();
      return (
        entry.name.toLowerCase().includes(lower) ||
        entry.description.toLowerCase().includes(lower)
      );
    }
    return true;
  });
}
